[rx]
spacecraft = GK-2A
mode = lrit
input = goesrecv
keys = EncryptionKeyMessage.bin

[output]
path = received
images = true
xrit = false
# 要忽略的 VCID 列表（例如 '4,5'）
#   - VCID 0：圆盘图（Full Disk）
#   - VCID 4：字母数字文本（Alpha-numeric Text）
#   - VCID 5：附加（非传感器）数据
channel_blacklist = 

[goesrecv]
#修改这个！
ip = 192.168.10.210

vchan = 5004

[osp]
ip = 127.0.0.1
vchan = 5001

[udp]
ip = 127.0.0.1
vchan = 5002

[dashboard]
enabled = true
port = 1692
interval = 1
